export const MORE_INFO = [
  {
    title: '[세모엔 6 / 김치앤칩스] 국제개발협력 취준생이라면 김치앤칩스 알고 가자',
    date: '2021. 8. 10.',
    tags: [{ id: 1, name: 'YouTube' }],
    link: 'https://www.youtube.com/watch?v=MFrwQ69r7QY&t=2s',
    thumbnail: '/images/intro_01.png',
    openInNewTab: true,
  },
  {
    title:
      '국제개발협력 분야에서 프리랜서로 활동하기 (국제개발 리얼라이브 12 - 김치앤칩스 오의석 #1)',
    date: '2021. 10. 20.',
    tags: [{ id: 2, name: 'YouTube' }],
    link: 'https://www.youtube.com/watch?v=6l1XIEJAGCc',
    thumbnail: '/images/intro_02.png',
    openInNewTab: true,
  },
  {
    title:
      '개발협력 뉴스레터 김치앤칩스를 알아보다 (국제개발 리얼라이브 13 - 김치앤칩스 오의석 #2)',
    date: ' 2021. 11. 11.',
    tags: [{ id: 3, name: 'YouTube' }],
    link: 'https://www.youtube.com/watch?v=_CU1N80Rv38',
    thumbnail: '/images/intro_03.png',
    openInNewTab: true,
  },
  {
    title: '뉴스레터 밖에서도 이어지는 구독자와의 관계 형성 #김치앤칩스',
    date: ' 2021. 3. 11.',
    tags: [{ id: 4, name: '스티비' }],
    link: 'https://blog.stibee.com/nyuseureteo-baggeseodo-ieojineun-gudogjawayi-gwangye-hyeongseong-gimciaencibseu/',
    thumbnail: '/images/intro_04.png',
    openInNewTab: true,
  },
  {
    title: '[2022 비영리스타트업 피칭데이] 공적인사적모임⭐살아있는 청년 국제 개발 협력 네트워크',
    date: ' 2022. 8. 22.',
    tags: [{ id: 5, name: 'YouTube' }],
    link: 'https://blog.stibee.com/nyuseureteo-baggeseodo-ieojineun-gudogjawayi-gwangye-hyeongseong-gimciaencibseu/',
    thumbnail: '/images/intro_05.png',
    openInNewTab: true,
  },
];

export const MEMBERS = [
  {
    team: '김칩',
    introduction: '김칩은 칩이다.',
    members: [
      {
        name: 'a',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'b',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'c',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'ooo',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'pppp',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'qqqq',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'ooo',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'pppp',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'qqqq',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'ooo',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'pppp',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'ooo',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'pppp',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'qqqq',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'ooo',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'pppp',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'qqqq',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'ooo',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'pppp',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
    ],
  },
  {
    team: 'IT',
    introduction: 'IT은 IT이다.',
    members: [
      {
        name: 'eee',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'fff',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'ggg',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'eee',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'eee',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'fff',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'ggg',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
    ],
  },
  {
    team: '홍보',
    introduction: '홍보는 홍보이다.',
    members: [
      {
        name: 'ooo',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'pppp',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'qqqq',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'ooo',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'pppp',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'qqqq',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'ooo',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'pppp',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'qqqq',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
    ],
  },
  {
    team: '행동',
    introduction: '행동은 행동이다.',
    members: [
      {
        name: 'rrr',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'sss',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
      {
        name: 'ttt',
        introduction: 'heheheh',
        link: 'https://www.google.com',
        image: '/images/contents_thumbnail.jpg',
      },
    ],
  },
];
